# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ooc/neutron_detection_simulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ooc/neutron_detection_simulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ooc/neutron_detection_simulation/CMakeFiles /home/ooc/neutron_detection_simulation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ooc/neutron_detection_simulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NEUTRON_DETECTION

# Build rule for target.
NEUTRON_DETECTION: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NEUTRON_DETECTION
.PHONY : NEUTRON_DETECTION

# fast build rule for target.
NEUTRON_DETECTION/fast:
	$(MAKE) -f CMakeFiles/NEUTRON_DETECTION.dir/build.make CMakeFiles/NEUTRON_DETECTION.dir/build
.PHONY : NEUTRON_DETECTION/fast

#=============================================================================
# Target rules for targets named neutron_detection

# Build rule for target.
neutron_detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neutron_detection
.PHONY : neutron_detection

# fast build rule for target.
neutron_detection/fast:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/build
.PHONY : neutron_detection/fast

neutron_detection.o: neutron_detection.cc.o

.PHONY : neutron_detection.o

# target to build an object file
neutron_detection.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/neutron_detection.cc.o
.PHONY : neutron_detection.cc.o

neutron_detection.i: neutron_detection.cc.i

.PHONY : neutron_detection.i

# target to preprocess a source file
neutron_detection.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/neutron_detection.cc.i
.PHONY : neutron_detection.cc.i

neutron_detection.s: neutron_detection.cc.s

.PHONY : neutron_detection.s

# target to generate assembly for a file
neutron_detection.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/neutron_detection.cc.s
.PHONY : neutron_detection.cc.s

src/3HeDetectorConstruction.o: src/3HeDetectorConstruction.cc.o

.PHONY : src/3HeDetectorConstruction.o

# target to build an object file
src/3HeDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/3HeDetectorConstruction.cc.o
.PHONY : src/3HeDetectorConstruction.cc.o

src/3HeDetectorConstruction.i: src/3HeDetectorConstruction.cc.i

.PHONY : src/3HeDetectorConstruction.i

# target to preprocess a source file
src/3HeDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/3HeDetectorConstruction.cc.i
.PHONY : src/3HeDetectorConstruction.cc.i

src/3HeDetectorConstruction.s: src/3HeDetectorConstruction.cc.s

.PHONY : src/3HeDetectorConstruction.s

# target to generate assembly for a file
src/3HeDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/3HeDetectorConstruction.cc.s
.PHONY : src/3HeDetectorConstruction.cc.s

src/3HeWorldConstruction.o: src/3HeWorldConstruction.cc.o

.PHONY : src/3HeWorldConstruction.o

# target to build an object file
src/3HeWorldConstruction.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/3HeWorldConstruction.cc.o
.PHONY : src/3HeWorldConstruction.cc.o

src/3HeWorldConstruction.i: src/3HeWorldConstruction.cc.i

.PHONY : src/3HeWorldConstruction.i

# target to preprocess a source file
src/3HeWorldConstruction.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/3HeWorldConstruction.cc.i
.PHONY : src/3HeWorldConstruction.cc.i

src/3HeWorldConstruction.s: src/3HeWorldConstruction.cc.s

.PHONY : src/3HeWorldConstruction.s

# target to generate assembly for a file
src/3HeWorldConstruction.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/3HeWorldConstruction.cc.s
.PHONY : src/3HeWorldConstruction.cc.s

src/4HeDetectorConstruction.o: src/4HeDetectorConstruction.cc.o

.PHONY : src/4HeDetectorConstruction.o

# target to build an object file
src/4HeDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/4HeDetectorConstruction.cc.o
.PHONY : src/4HeDetectorConstruction.cc.o

src/4HeDetectorConstruction.i: src/4HeDetectorConstruction.cc.i

.PHONY : src/4HeDetectorConstruction.i

# target to preprocess a source file
src/4HeDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/4HeDetectorConstruction.cc.i
.PHONY : src/4HeDetectorConstruction.cc.i

src/4HeDetectorConstruction.s: src/4HeDetectorConstruction.cc.s

.PHONY : src/4HeDetectorConstruction.s

# target to generate assembly for a file
src/4HeDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/4HeDetectorConstruction.cc.s
.PHONY : src/4HeDetectorConstruction.cc.s

src/BF3DetectorConstruction.o: src/BF3DetectorConstruction.cc.o

.PHONY : src/BF3DetectorConstruction.o

# target to build an object file
src/BF3DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/BF3DetectorConstruction.cc.o
.PHONY : src/BF3DetectorConstruction.cc.o

src/BF3DetectorConstruction.i: src/BF3DetectorConstruction.cc.i

.PHONY : src/BF3DetectorConstruction.i

# target to preprocess a source file
src/BF3DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/BF3DetectorConstruction.cc.i
.PHONY : src/BF3DetectorConstruction.cc.i

src/BF3DetectorConstruction.s: src/BF3DetectorConstruction.cc.s

.PHONY : src/BF3DetectorConstruction.s

# target to generate assembly for a file
src/BF3DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/BF3DetectorConstruction.cc.s
.PHONY : src/BF3DetectorConstruction.cc.s

src/HistogramsAnalysisManager.o: src/HistogramsAnalysisManager.cc.o

.PHONY : src/HistogramsAnalysisManager.o

# target to build an object file
src/HistogramsAnalysisManager.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/HistogramsAnalysisManager.cc.o
.PHONY : src/HistogramsAnalysisManager.cc.o

src/HistogramsAnalysisManager.i: src/HistogramsAnalysisManager.cc.i

.PHONY : src/HistogramsAnalysisManager.i

# target to preprocess a source file
src/HistogramsAnalysisManager.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/HistogramsAnalysisManager.cc.i
.PHONY : src/HistogramsAnalysisManager.cc.i

src/HistogramsAnalysisManager.s: src/HistogramsAnalysisManager.cc.s

.PHONY : src/HistogramsAnalysisManager.s

# target to generate assembly for a file
src/HistogramsAnalysisManager.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/HistogramsAnalysisManager.cc.s
.PHONY : src/HistogramsAnalysisManager.cc.s

src/NeutronActionInitialization.o: src/NeutronActionInitialization.cc.o

.PHONY : src/NeutronActionInitialization.o

# target to build an object file
src/NeutronActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronActionInitialization.cc.o
.PHONY : src/NeutronActionInitialization.cc.o

src/NeutronActionInitialization.i: src/NeutronActionInitialization.cc.i

.PHONY : src/NeutronActionInitialization.i

# target to preprocess a source file
src/NeutronActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronActionInitialization.cc.i
.PHONY : src/NeutronActionInitialization.cc.i

src/NeutronActionInitialization.s: src/NeutronActionInitialization.cc.s

.PHONY : src/NeutronActionInitialization.s

# target to generate assembly for a file
src/NeutronActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronActionInitialization.cc.s
.PHONY : src/NeutronActionInitialization.cc.s

src/NeutronPrimaryGeneratorAction.o: src/NeutronPrimaryGeneratorAction.cc.o

.PHONY : src/NeutronPrimaryGeneratorAction.o

# target to build an object file
src/NeutronPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronPrimaryGeneratorAction.cc.o
.PHONY : src/NeutronPrimaryGeneratorAction.cc.o

src/NeutronPrimaryGeneratorAction.i: src/NeutronPrimaryGeneratorAction.cc.i

.PHONY : src/NeutronPrimaryGeneratorAction.i

# target to preprocess a source file
src/NeutronPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronPrimaryGeneratorAction.cc.i
.PHONY : src/NeutronPrimaryGeneratorAction.cc.i

src/NeutronPrimaryGeneratorAction.s: src/NeutronPrimaryGeneratorAction.cc.s

.PHONY : src/NeutronPrimaryGeneratorAction.s

# target to generate assembly for a file
src/NeutronPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronPrimaryGeneratorAction.cc.s
.PHONY : src/NeutronPrimaryGeneratorAction.cc.s

src/NeutronRunAction.o: src/NeutronRunAction.cc.o

.PHONY : src/NeutronRunAction.o

# target to build an object file
src/NeutronRunAction.cc.o:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronRunAction.cc.o
.PHONY : src/NeutronRunAction.cc.o

src/NeutronRunAction.i: src/NeutronRunAction.cc.i

.PHONY : src/NeutronRunAction.i

# target to preprocess a source file
src/NeutronRunAction.cc.i:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronRunAction.cc.i
.PHONY : src/NeutronRunAction.cc.i

src/NeutronRunAction.s: src/NeutronRunAction.cc.s

.PHONY : src/NeutronRunAction.s

# target to generate assembly for a file
src/NeutronRunAction.cc.s:
	$(MAKE) -f CMakeFiles/neutron_detection.dir/build.make CMakeFiles/neutron_detection.dir/src/NeutronRunAction.cc.s
.PHONY : src/NeutronRunAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... NEUTRON_DETECTION"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... neutron_detection"
	@echo "... install"
	@echo "... neutron_detection.o"
	@echo "... neutron_detection.i"
	@echo "... neutron_detection.s"
	@echo "... src/3HeDetectorConstruction.o"
	@echo "... src/3HeDetectorConstruction.i"
	@echo "... src/3HeDetectorConstruction.s"
	@echo "... src/3HeWorldConstruction.o"
	@echo "... src/3HeWorldConstruction.i"
	@echo "... src/3HeWorldConstruction.s"
	@echo "... src/4HeDetectorConstruction.o"
	@echo "... src/4HeDetectorConstruction.i"
	@echo "... src/4HeDetectorConstruction.s"
	@echo "... src/BF3DetectorConstruction.o"
	@echo "... src/BF3DetectorConstruction.i"
	@echo "... src/BF3DetectorConstruction.s"
	@echo "... src/HistogramsAnalysisManager.o"
	@echo "... src/HistogramsAnalysisManager.i"
	@echo "... src/HistogramsAnalysisManager.s"
	@echo "... src/NeutronActionInitialization.o"
	@echo "... src/NeutronActionInitialization.i"
	@echo "... src/NeutronActionInitialization.s"
	@echo "... src/NeutronPrimaryGeneratorAction.o"
	@echo "... src/NeutronPrimaryGeneratorAction.i"
	@echo "... src/NeutronPrimaryGeneratorAction.s"
	@echo "... src/NeutronRunAction.o"
	@echo "... src/NeutronRunAction.i"
	@echo "... src/NeutronRunAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

